name: Add SSH Key
on:
  workflow_dispatch:
jobs:
  add-key:
    runs-on: ubuntu-latest
    steps:
      - name: Add public key to server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.STONEX_DEPLOY_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo "${{ secrets.STONEX_SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          ssh -i ~/.ssh/deploy_key -o IdentitiesOnly=yes x-001@115.29.237.229 \
            "echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPf4YuUJi5kN7C45jG3r+HMv6JhMQ3HWsH8T7PxNL7Fz 1300252737-ops@github' >> ~/.ssh/authorized_keys && echo 'key added'"
